# Generated by Django 5.2.6 on 2026-09-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('category', models.CharField(choices=[('agriculture', 'Agriculture'), ('infrastructure', 'Infrastructure'), ('regulatory', 'Regulatory'), ('technology', 'Technology'), ('industry', 'Industry News'), ('general', 'General')], default='general', max_length=50)),
                ('excerpt', models.TextField(help_text='Short preview shown on the blog listing page')),
                ('content', models.TextField(help_text='Full article content — supports plain text or HTML')),
                ('author', models.CharField(blank=True, default='Aeronica Team', max_length=255)),
                ('read_time', models.PositiveIntegerField(default=5, help_text='Estimated read time in minutes')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from website')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('published_at', models.DateField(help_text='Publication date shown on the article')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['order', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('category', models.CharField(choices=[('agriculture', 'Agriculture'), ('government', 'Government'), ('infrastructure', 'Infrastructure'), ('defense', 'Defense'), ('mining', 'Mining'), ('smart-city', 'Smart City'), ('utility', 'Utility'), ('locust-control', 'Locust Control')], max_length=50)),
                ('summary', models.TextField(help_text='Short description shown on the listing card')),
                ('content', models.TextField(help_text='Full detail content — supports plain text or HTML')),
                ('client', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from website')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order', '-date'],
            },
        ),
    ]
